CREATE TABLE IF NOT EXISTS public.customer (
    -- 'generated by default as identity' is the modern, standard way to create auto-incrementing keys in PostgreSQL.
                                               customer_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- text is often preferred over varchar in PostgreSQL unless you have a strict length requirement.
                                               name text NOT NULL,

    -- Adding a UNIQUE constraint is a good practice for emails.
                                               email text NOT NULL UNIQUE,

                                               mobile_number text NOT NULL,

    -- 'timestamptz' (timestamp with time zone) is the best practice for timestamps.
    -- 'default now()' automatically sets the creation time.
                                               created_at timestamptz DEFAULT now() NOT NULL,

    -- 'uuid' is the correct type to reference Supabase users.
    -- 'auth.uid()' automatically inserts the ID of the logged-in user.
                                               created_by uuid REFERENCES auth.users(id) DEFAULT auth.uid() NOT NULL,

                                               updated_at timestamptz,

                                               updated_by uuid REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.accounts (
    -- Primary Key using the modern identity generation.
                                               account_number int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- This creates a Foreign Key relationship to the 'customer' table.
    -- It ensures that every account MUST be linked to a valid customer.
    -- 'ON DELETE CASCADE' means if you delete a customer, all of their associated accounts will be deleted automatically.
                                               customer_id int NOT NULL REFERENCES public.customer(customer_id) ON DELETE CASCADE,

                                               account_type text NOT NULL,
                                               branch_address text NOT NULL,

    -- Automatic timestamping for creation date.
                                               created_at timestamptz DEFAULT now() NOT NULL,

    -- Automatic user tracking, linked to the logged-in Supabase user.
                                               created_by uuid REFERENCES auth.users(id) DEFAULT auth.uid() NOT NULL,

    -- Timestamps and user tracking for updates.
                                               updated_at timestamptz,
                                               updated_by uuid REFERENCES auth.users(id)
);